### ISSUE TITLE
Publish TypeScript types for this package

### ISSUE THREAD

**Issue by blimmer** [samvera/node-iiif#35]
Self-explanatory. It'd be nice to have types delivered natively with this package, but we could also go the [`DefinitelyTyped` route](https://github.com/DefinitelyTyped/DefinitelyTyped), as well.

**Comment by mbklein** [comment]
@blimmer I've taken a stab at adding the appropriate `.d.ts` files. VS Code's Intellisense is picking up the types nicely in my tests, but since I'm a bit new at combining JS code and TS types in a single package, would you mind referencing the branch from a project and seeing if it's behaving as you'd expect?

```
"dependencies": {
  "iiif-processor": "github:samvera/node-iiif#35-add-typescript-types"
}
```

**Comment by blimmer** [comment]
Thanks! Looking good so far. I tried this on a repo using this package and found only one issue with the `streamResolver`.
